[pytest]
; Indica a Pytest dónde buscar los tests.
testpaths = tests
; Indica a Pytest qué archivos considerar como tests.
python_files = test_*.py
; Indica a Pytest dónde buscar los módulos Python.
pythonpath = .